### ISSUE TITLE
Can't find the effect

### ISSUE THREAD

**Issue by RoccoFortuna** [DeepMakeStudio/DeepMake#2]
Hi, I'm new to After Effects and struggling to get this to work.
I followed the installation readme:
- cloned the repo, cd'd into it, created the conda env `conda env create -f environment.yml`,
- cd'd into plugins, cloned `git clone https://github.com/DeepMakeStudio/Diffusers`, created the conda env `conda env create -f plugin/Diffusers/environment_mac.yml `

Then:
- downloaded the Binaries_Mac.zip file the zip, unzipped,
    - placed the .bundle file as described under: `/Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/DeepMake_ae.bundle`, 
    - placed the `appPrompt.app` under: `/Applications/appPrompt.app`

Finally:
- conda activate deepmake
- python startup.py
getting:
```
(deepmake) username DeepMake % python startup.py      
INFO:     Started server process [18562]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
[2023-12-16 00:41:18,917] INFO:huey.consumer:MainThread:Huey consumer started with 1 thread, PID 18563 at 2023-12-15 23:41:18.917322
[2023-12-16 00:41:18,917] INFO:huey.consumer:MainThread:Scheduler runs every 1 second(s).
[2023-12-16 00:41:18,917] INFO:huey.consumer:MainThread:Periodic tasks are enabled.
[2023-12-16 00:41:18,917] INFO:huey.consumer:MainThread:The following commands are available:
+ main.huey_call_endpoint
```

Opened After Effects, but I can't find the effect. I looked under Window->Effects & Presets, or in Effect->Manage Effects... 
Where is it supposed to show up or what am I missing? 
Thank you!

**Comment by bryanlyon** [comment]
You should see it under Effect/DeepMake/AI Plugin Renderer.  See the screenshot for a visual.

[Screenshot 2023-12-18 102842](https://github.com/DeepMakeStudio/DeepMake/assets/3223233/7e1ff0bc-353f-4984-9409-a83dbc7bc49d)

If it's not showing up, please make sure you installed in the correct folder.  If you open a console and do `ls "/Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/"` you should see both DeepMake_ae.bundle and dummy.txt (the dummy.txt is placed their by After Effects).  Please let me know if this didn't help and we can troubleshoot further.

**Comment by RoccoFortuna** [comment]
Yeah no, it's not showing up in Effect:
<img width="390" alt="image" src="https://github.com/DeepMakeStudio/DeepMake/assets/32480249/d0ee4db4-d3d4-4f54-a7da-7aeb9eb84a97">

`ls "/Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/"` does output:
`DeepMake_ae.bundle`

**Comment by bryanlyon** [comment]
If it doesn't have the dummy.txt then After Effects may be expecting the plugin to be in a different place.  Can you check if there are any files under "/Library/Application Support/Adobe/Common/Plug-ins/" (Best way to do this is to use `find /Library/Application Support/Adobe/Common/Plug-ins/ -type f` )
